apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allocator-rb
  namespace: starx
subjects:
  - kind: ServiceAccount
    name: allocator-sa
    namespace: starx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allocator-role
