name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.go'
      - '.github/workflows/test.yml'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Verify build
        run: go build ./...

      - name: Run unit tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Show coverage summary
        run: go tool cover -func=coverage.txt
